[workspace]

[package]
name = "iota-client"
version = "0.1.0-test.0"
authors = ["Bing-Yang Lin <bingyang.lin@iota.org>"]
edition = "2018"
description = "Client library of IOTA"
license = "Apache-2.0"
repository = "https://github.com/iotaledger/iota.rs"
homepage = "https://iota.org"
readme = "README.md"

[lib]
name = "iota_client"
crate-type = ["cdylib"]

[dependencies]
tokio = { version = "1.1", features = ["macros"] }
hex = "0.4"
iota-client = { path = "../../../iota-client", features = ["mqtt"] }
dict_derive = "0.3.0"
serde_json = "1.0"
once_cell = "1.4"
futures = "0.3"

[dependencies.pyo3]
version = "0.13"
features = ["extension-module", "abi3-py36"]
